### ISSUE TITLE
Nuget Support!

### ISSUE THREAD

**Issue by MrScautHD** [amerkoleci/alimer#18]
Hello i love your Lib and i would love to work with it!

Can you maybe upload it on Nuget?

**Comment by roy-t** [comment]
Hey, Vortice is on Nuget, or are you missing a library or version? https://www.nuget.org/packages?q=vortice

**Comment by amerkoleci** [comment]
> Hey, Vortice is on Nuget, or are you missing a library or version? https://www.nuget.org/packages?q=vortice

Probably he meant libraries from this game engine (not Vortice.Windows or Vortice.Vulkan)

**Comment by MrScautHD** [comment]
> > Hey, Vortice is on Nuget, or are you missing a library or version? https://www.nuget.org/packages?q=vortice
> 
> Probably he meant libraries from this game engine (not Vortice.Windows or Vortice.Vulkan)

yea, would it possible?
