### ISSUE TITLE
WebGPU support.

### ISSUE THREAD

**Issue by hugo-sna** [amerkoleci/alimer#20]
This is not really a feature request, just a suggestion. Instead of using DirectX/Vulkan/OpenGL you could use WebGPU. Why WebGPU? It's a performant crossplatform graphics API (doesn't only support web). I thought it might interest you so you don't have to write a backend for each graphics API.

**Comment by amerkoleci** [comment]
Hi,
Thanks for suggestion, I'm already aware of WebGPU, indeed I'm maintaining bindings for that https://github.com/amerkoleci/Alimer.Bindings.WebGPU

I like WebGPU but it's also missing stuff like raytracing, bindless, fsr2 integration etc
